name: Aqua and Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      destroy_resources:
        description: 'Trigger resource destruction'
        required: true
        default: 'false'

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init

      - name: Manual Approval for Destroy
        if: ${{ github.event.inputs.destroy_resources == 'true' }}
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GH_TOKEN }}
          approvers: sonnambulo

      - name: Destroy Terraform Resources
        if: ${{ github.event.inputs.destroy_resources == 'true' }}
        run: terraform destroy -auto-approve
